### ISSUE TITLE
Issue in the NLOSClassification README file

### ISSUE THREAD

**Issue by JuSquare** [ewine-project/UWB-localization#2]
Hi,

Just to report that the python code is not correct in the README file. Preamble count is stored in *item[9]*. Since the text is not clear whether the list of features stored in each column is in the right order or not, it's a bit confusing. The python code should be:

	import uwb_dataset
	
	# import raw data
	data = uwb_dataset.import_from_files()
	
	# divide CIR by RXPACC RX preamble count (get CIR of single preamble pulse)
	# item[9] represents number of acquired preamble symbols
	for item in data:
		item[15:] = item[15:]/float(item[9])
	
	print(data)

Thanks! And great job on the paper!
Cheers
Julien

**Comment by JaronFontaine** [comment]
@JuSquare Thank you for this remark on the readme of the dataset! The features described are indeed in order of each column in the header of the .csv files. As a result, RXPACC is indeed item[9]. I have updated the readme and marked this issue as closed.
